pipeline {
  agent {
    docker {
      image 'node:10'
      label 'Linux'
    }
  }
  parameters {
    string(name: 'TargetDirectory', defaultValue: 'asterics-web-devlinux', description: 'Target directory name (Deploy)', choices: 'asterics-web-devlinux\nasterics-web-production')
  }
  environment {
    SERVER = credentials('studyathome')
  }
  stages {
    stage('Source') {
      steps {
        git branch: env.BRANCH_NAME, url: 'https://github.com/asterics/asterics-web'
      }
    }
    stage('Build') {
      steps {
        sh '''
          npm install --prefix ./asterics-web-vue
          npm run build --prefix ./asterics-web-vue
        '''
      }
    }
    stage('Deploy') {
      steps {
        sh "ln -sf ./asterics-web-vue/dist ${params.TargetDirecotry}"
        script {
          def remote = [ name: 'studyathome', host: 'studyathome.technikum-wien.at', user: $SERVER_USR, password: $SERVER_PSW, allowAnyHosts: true ]
          sshRemove remote: remote, path: "/var/www/html/${destination}", failOnError: false
          sshPut remote: remote, from: destination, into: '/var/www/html/'
        }
      }
    }
  }
  post {
    always {
      cleanWs cleanWhenAborted: false, cleanWhenFailure: false, cleanWhenNotBuilt: false
    }
  }
}